variable date

diff --git a/08-Install-Mysql b/08-Install-Mysql
--- a/08-Install-Mysql
+++ b/08-Install-Mysql
@@ -21,3 +21,14 @@ if [ $? -ne 0 ]
   else 
     echo "installation of mysql is success"
 fi     
+
+## nstallation of post fix 
+ yum install postfix -y
+
+if [ $? -ne 0 ]
+  then 
+     echo "installation of postfix is error"
+     exit 1
+  else 
+    echo "installation of postfix is success"
+fi   
