variable date

diff --git a/08-Install-Mysql b/08-Install-Mysql
--- a/08-Install-Mysql
+++ b/08-Install-Mysql
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+ # our goal is to install the mysql
 
 USERID=$(id -u)
 
@@ -10,5 +11,13 @@ if [ $USERID -ne 0 ]
   #else
     #echo "Info:you are root access" 
 fi 
-
+## it i sour responsibility again check the installation is success or not 
 yum install mysqllll -y 
+
+if [ $? -ne 0]
+  then 
+     echo "installation of mysql is error"
+     exit 1
+  else 
+    echo "installation of mysql is success"
+fi     
